### ISSUE TITLE
Is it possible to add paging function to BrickCols.js?

### ISSUE THREAD

**Issue by e1blue** [ms27/BrickCols.js#2]
Is it possible to add paging function to BrickCols.js?

**Comment by ms27** [comment]
BrickCols.js - just for aligning blocks. If you are looking for pagination functionality, there are many libraries that solve the problem… you just need to use [one](http://pagination.js.org/) of them and call BrickCols.js in a callback function.
But if you want you can make a pull rquest with new paging function only for _brickcols​[.min].js_, but not for _brickcols.light_ version :)

PS: Did you write [this](http://javascript-demo.w3c.tokyo/demo/layout/brickcols.js/2.1.0/21/)?)
*http://javascript-demo.w3c.tokyo/demo/layout/brickcols.js/2.1.0/21/
